- name: Deploy to EC2
  run: |
    ssh ubuntu@54.227.208.98 << 'EOF'
      set -e  # Exit on any command failure
      echo "Starting deployment process..."

      # Update repo with latest code
      if [ ! -d "/home/ubuntu/docker-todo" ]; then
        echo "Cloning repository..."
        git clone git@github.com:amitbiswas1992/docker-todo.git /home/ubuntu/docker-todo
      else
        echo "Pulling latest changes..."
        cd /home/ubuntu/docker-todo
        git pull origin master
      fi

      # Ensure Docker permissions are correct
      echo "Setting Docker socket permissions..."
      sudo chmod 666 /var/run/docker.sock

      # Build the Docker image
      echo "Building Docker image..."
      cd /home/ubuntu/docker-todo
      sudo docker build -t todo-list-app .

      # Stop and remove any old container
      echo "Stopping and removing old container..."
      sudo docker stop todo-list-app || true
      sudo docker rm todo-list-app || true

      # Run the new container
      echo "Running new container..."
      sudo docker run -d -p 80:3000 --name todo-list-app todo-list-app

      # Optional: Clean up old Docker images
      echo "Cleaning up unused Docker images..."
      sudo docker image prune -a -f || true

      echo "Deployment completed successfully."
    EOF
