name: Deploy to AWS EC2

on:
  push:
    branches:
      - master  # Trigger deployment when changes are pushed to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH access for deployment
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      # Step 3: Deploy and manage code on EC2
      - name: Deploy to EC2
        run: |
          ssh ubuntu@54.227.208.98 << 'EOF'
            set -e  # Stop script if any command fails
            echo "Starting deployment process..."

            # Navigate to the app directory or clone the repo if not present
            if [ ! -d "/home/ubuntu/todo-list-app" ]; then
              echo "Cloning repository..."
              git clone git@github.com:amitbiswas1992/docker-todo.git /home/ubuntu/todo-list-app
            else
              echo "Pulling latest changes..."
              cd /home/ubuntu/todo-list-app
              git pull origin master
            fi

            # Navigate to the app directory
            cd /home/ubuntu/todo-list-app

            # Build the Docker image
            echo "Building Docker image..."
            sudo docker build -t todo-list-app .

            # Stop and remove the old container if it's running
            echo "Stopping and removing old container..."
            sudo docker stop todo-list-app || true
            sudo docker rm todo-list-app || true

            # Run the new container
            echo "Running the new Docker container..."
            sudo docker run -d -p 80:3000 --name todo-list-app todo-list-app

            echo "Deployment completed successfully."
          EOF
